services:
  strapi:
    build: .
    image: mosonata/tolen-pos-api
    restart: unless-stopped
    env_file: ./.env.production
   # We comment this line because we passing the env from envFile paramter
    # environment:
    #   DATABASE_CLIENT: ${DATABASE_CLIENT}
    #   DATABASE_HOST: strapiDB
    #   DATABASE_PORT: ${DATABASE_PORT}
    #   DATABASE_NAME: ${DATABASE_NAME}
    #   DATABASE_USERNAME: ${DATABASE_USERNAME}
    #   DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    #   JWT_SECRET: ${JWT_SECRET}
    #   ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
    #   APP_KEYS: ${APP_KEYS}
    #   NODE_ENV: ${NODE_ENV}
    #   DOWNLOAD_METRICS_PATH: /app/data/metrics
    deploy:
      replicas: 3
      # placement:
      #   max_replicas_per_node: 1
      update_config:
        parallelism: 3
        delay: 50s
      restart_policy:
        condition: on-failure
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./public/uploads:/opt/app/public/uploads
      # this is the path of the data on the gdrive
    ports:
      - "1334:1334"
   # also we comment this because we using docker Swarm 
    # networks:
    #   - strapi
    depends_on:
      - tolenPosDb

  tolenPosDb:
    restart: unless-stopped
    env_file: ./.env.production
    image: postgres:latest
    environment:
      POSTGRES_USER: tolenpos
      POSTGRES_PASSWORD: AddingIt
      POSTGRES_DB: tolen_pos_db
    volumes:
      - strapi-tolen-data:/var/lib/postgresql
    ports:
      - "5439:5432"
      # also we comment this because we using docker Swarm 
    # networks:
    #   - strapi

volumes:
  strapi-tolen-data:

