/**
 * Refund Record Types
 * Type definitions for refund security system
 */

export interface RefundItemData {
  productId: string;
  productName: string;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
}

export interface RefundRecordInput {
  originalReceiptNumber: string;
  transactionId: string;
  refundType: 'full' | 'partial';
  refundAmount: number;
  requestedByUserId: number;
  requestedByUsername: string;
  managerPin: string; // 6-digit PIN generated by POS client
  reason: string;
  refundTimestamp?: string;
  terminalId: string;
  hoursSinceOriginalSale?: number;
  itemsRefunded: RefundItemData[];
}

export interface RefundRecordComponent extends RefundRecordInput {
  status: 'pending' | 'approved' | 'rejected';
  requestedAt: string;
  approvedByUserId?: number;
  approvedByUsername?: string;
  approvedByRole?: 'admin' | 'manager';
}

export interface AddRefundRecordResult {
  success: boolean;
  error?: string;
  refundRecordId?: string;
  notificationSent?: boolean;
  sentToDevices?: number;
}
